name: Pull Request Checks
on:
  push:
    branches-ignore:
      - main
jobs:
  pr_checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Setup poetry environment
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root
      - name: Setup terragrunt and terraform
        run: |
          scripts/./install_infra_tools.sh
      - name: Run pre-commit checks
        run: |
          poetry run pre-commit run --all-files
      - name: Run infra plan
        run: |
          pushd infra/live/dev
          terragrunt run-all init --terragrunt-non-interactive
          terragrunt run-all plan --terragrunt-non-interactive
          popd
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
